linearham: linearham::NTInsertion Class Reference
linearham::NTInsertion Class Reference
A class holding non-templated insertion (NTI) HMM information extracted from a partis YAML file. This information is used to compute (Simple|Phylo)HMM path probabilities.
#include <NTInsertion.hpp>
Public Member Functions
NTInsertion (const YAML::Node &root)
Constructor for NTInsertion starting from a partis YAML file.
const Eigen::VectorXd & nti_landing_in () const
const Eigen::MatrixXd & nti_landing_out () const
const Eigen::MatrixXd & nti_transition () const
const Eigen::MatrixXd & nti_emission () const
Protected Attributes
Eigen::VectorXd nti_landing_in_
Eigen::MatrixXd nti_landing_out_
Eigen::MatrixXd nti_transition_
Eigen::MatrixXd nti_emission_
Detailed Description
A class holding non-templated insertion (NTI) HMM information extracted from a partis YAML file. This information is used to compute (Simple|Phylo)HMM path probabilities.
Definition at line 18 of file NTInsertion.hpp.
Constructor & Destructor Documentation
NTInsertion()
linearham::NTInsertion::NTInsertion (const YAML::Node & root)
Constructor for NTInsertion starting from a partis YAML file.
Parameters
[in] root A root node associated with a partis YAML file.
Definition at line 21 of file NTInsertion.cpp.
References linearham::FindGermlineStartEnd(), linearham::GetAlphabet(), linearham::GetAlphabetIndex(), linearham::GetGermlineStateRegex(), linearham::GetNTIStateRegex(), nti_emission_, nti_landing_in_, nti_landing_out_, nti_transition_, and linearham::ParseStringProbMap().
Member Function Documentation
nti_emission()
const Eigen::MatrixXd& linearham::NTInsertion::nti_emission () const inline
Definition at line 42 of file NTInsertion.hpp.
References nti_emission_.
nti_landing_in()
const Eigen::VectorXd& linearham::NTInsertion::nti_landing_in () const inline
Definition at line 39 of file NTInsertion.hpp.
References nti_landing_in_.
nti_landing_out()
const Eigen::MatrixXd& linearham::NTInsertion::nti_landing_out () const inline
Definition at line 40 of file NTInsertion.hpp.
References nti_landing_out_.
nti_transition()
const Eigen::MatrixXd& linearham::NTInsertion::nti_transition () const inline
Definition at line 41 of file NTInsertion.hpp.
References nti_transition_.
Member Data Documentation
nti_emission_
Eigen::MatrixXd linearham::NTInsertion::nti_emission_ protected
Definition at line 31 of file NTInsertion.hpp.
Referenced by nti_emission(), and NTInsertion().
nti_landing_in_
Eigen::VectorXd linearham::NTInsertion::nti_landing_in_ protected
Definition at line 21 of file NTInsertion.hpp.
Referenced by nti_landing_in(), and NTInsertion().
nti_landing_out_
Eigen::MatrixXd linearham::NTInsertion::nti_landing_out_ protected
Definition at line 23 of file NTInsertion.hpp.
Referenced by nti_landing_out(), and NTInsertion().
nti_transition_
Eigen::MatrixXd linearham::NTInsertion::nti_transition_ protected
Definition at line 28 of file NTInsertion.hpp.
Referenced by nti_transition(), and NTInsertion().
The documentation for this class was generated from the following files:
src/NTInsertion.hpp
src/NTInsertion.cpp