linearham: linearham::SimpleHMM Class Reference
linearham::SimpleHMM Class Reference
A star tree HMM implementation (similar to that found in partis). This derived class is used to compute the star tree emission probabilities from partis HMM germline parameter files.
#include <SimpleHMM.hpp>
Public Member Functions
SimpleHMM (const std::string &yaml_path, int cluster_ind, const std::string &hmm_param_dir, int seed)
SimpleHMM constructor.
Public Member Functions inherited from linearham::HMM
HMM (const std::string &yaml_path, int cluster_ind, const std::string &hmm_param_dir, int seed)
Constructor for HMM that is called from the (Simple|Phylo)HMM constructor.
const std::string & locus () const
const YAML::Node & cluster_data () const
const std::map< std::string, std::pair< int, int > > & flexbounds () const
const std::map< std::string, int > & relpos () const
const std::unordered_map< std::string, GermlineGene > & ggenes () const
const std::string & alphabet () const
const Eigen::MatrixXi & msa () const
const std::mt19937 & rng () const
const std::discrete_distribution< int > & distr () const
const std::map< std::string, std::pair< int, int > > & vpadding_ggene_ranges () const
const std::vector< int > & vpadding_naive_bases () const
const std::vector< int > & vpadding_site_inds () const
const std::vector< std::string > & vgerm_state_strs () const
const std::vector< int > & vgerm_left_del () const
const std::vector< int > & vgerm_right_del () const
const std::map< std::string, std::pair< int, int > > & vgerm_ggene_ranges () const
const std::vector< int > & vgerm_naive_bases () const
const std::vector< int > & vgerm_germ_inds () const
const std::vector< int > & vgerm_site_inds () const
const std::vector< std::string > & vd_junction_state_strs () const
const std::vector< int > & vd_junction_del () const
const std::vector< GermlineType > & vd_junction_ggene_types () const
const std::map< std::string, std::pair< int, int > > & vd_junction_ggene_ranges () const
const std::vector< int > & vd_junction_naive_bases () const
const std::vector< int > & vd_junction_germ_inds () const
const std::vector< int > & vd_junction_site_inds () const
const std::vector< std::string > & dgerm_state_strs () const
const std::vector< int > & dgerm_left_del () const
const std::vector< int > & dgerm_right_del () const
const std::map< std::string, std::pair< int, int > > & dgerm_ggene_ranges () const
const std::vector< int > & dgerm_naive_bases () const
const std::vector< int > & dgerm_germ_inds () const
const std::vector< int > & dgerm_site_inds () const
const std::vector< std::string > & dj_junction_state_strs () const
const std::vector< int > & dj_junction_del () const
const std::vector< GermlineType > & dj_junction_ggene_types () const
const std::map< std::string, std::pair< int, int > > & dj_junction_ggene_ranges () const
const std::vector< int > & dj_junction_naive_bases () const
const std::vector< int > & dj_junction_germ_inds () const
const std::vector< int > & dj_junction_site_inds () const
const std::vector< std::string > & jgerm_state_strs () const
const std::vector< int > & jgerm_left_del () const
const std::vector< int > & jgerm_right_del () const
const std::map< std::string, std::pair< int, int > > & jgerm_ggene_ranges () const
const std::vector< int > & jgerm_naive_bases () const
const std::vector< int > & jgerm_germ_inds () const
const std::vector< int > & jgerm_site_inds () const
const std::map< std::string, std::pair< int, int > > & jpadding_ggene_ranges () const
const std::vector< int > & jpadding_naive_bases () const
const std::vector< int > & jpadding_site_inds () const
const Eigen::RowVectorXd & vpadding_transition () const
const Eigen::MatrixXd & vgerm_vd_junction_transition () const
const Eigen::MatrixXd & vd_junction_transition () const
const Eigen::MatrixXd & vd_junction_dgerm_transition () const
const Eigen::MatrixXd & dgerm_dj_junction_transition () const
const Eigen::MatrixXd & dj_junction_transition () const
const Eigen::MatrixXd & dj_junction_jgerm_transition () const
const Eigen::RowVectorXd & jpadding_transition () const
const Eigen::RowVectorXd & vpadding_emission () const
const Eigen::RowVectorXd & vgerm_emission () const
const Eigen::MatrixXd & vd_junction_emission () const
const Eigen::RowVectorXd & dgerm_emission () const
const Eigen::MatrixXd & dj_junction_emission () const
const Eigen::RowVectorXd & jgerm_emission () const
const Eigen::RowVectorXd & jpadding_emission () const
bool cache_forward () const
const Eigen::RowVectorXd & vgerm_forward () const
const Eigen::MatrixXd & vd_junction_forward () const
const Eigen::RowVectorXd & dgerm_forward () const
const Eigen::MatrixXd & dj_junction_forward () const
const Eigen::RowVectorXd & jgerm_forward () const
int vgerm_scaler_count () const
const std::vector< int > & vd_junction_scaler_counts () const
int dgerm_scaler_count () const
const std::vector< int > & dj_junction_scaler_counts () const
int jgerm_scaler_count () const
const std::string & naive_seq_samp () const
const std::string & vgerm_state_str_samp () const
int vgerm_state_ind_samp () const
int vgerm_left_del_samp () const
int vgerm_right_del_samp () const
const std::string & vgerm_left_insertion_samp () const
const std::vector< std::string > & vd_junction_state_str_samps () const
const std::vector< int > & vd_junction_state_ind_samps () const
const std::string & vd_junction_insertion_samp () const
const std::string & dgerm_state_str_samp () const
int dgerm_state_ind_samp () const
int dgerm_left_del_samp () const
int dgerm_right_del_samp () const
const std::vector< std::string > & dj_junction_state_str_samps () const
const std::vector< int > & dj_junction_state_ind_samps () const
const std::string & dj_junction_insertion_samp () const
const std::string & jgerm_state_str_samp () const
int jgerm_state_ind_samp () const
int jgerm_left_del_samp () const
int jgerm_right_del_samp () const
const std::string & jgerm_right_insertion_samp () const
double LogLikelihood ()
Computes the HMM log-likelihood.
std::string SampleNaiveSequence ()
Samples a HMM hidden state path (i.e. a naive sequence).
Private Member Functions
void InitializeEmission () override
Initializes the emission probability matrices under the star tree assumption.
void FillGermlineEmission (const std::map< std::string, std::pair< int, int >> &ggene_ranges_, const std::vector< int > &germ_inds_, const std::vector< int > &site_inds_, Eigen::RowVectorXd &emission_, int &scaler_count_) const
Fills the "germline" emission probability row vector under the star tree assumption.
void FillJunctionEmission (const std::map< std::string, std::pair< int, int >> &ggene_ranges_, const std::vector< int > &naive_bases_, const std::vector< int > &germ_inds_, const std::vector< int > &site_inds_, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, Eigen::MatrixXd &emission_) const
Fills the "junction" emission probability matrix under the star tree assumption.
void FillPaddingEmission (const std::map< std::string, std::pair< int, int >> &ggene_ranges_, const std::vector< int > &site_inds_, Eigen::RowVectorXd &emission_, int &scaler_count_) const
Fills the "padding" emission probability row vector associated with the adjacent "germline" region under the star tree assumption.
Additional Inherited Members
Protected Member Functions inherited from linearham::HMM
void InitializeMsa ()
Initializes the clonal family sequence alignment from the partis output YAML file.
void InitializeStateSpace ()
Initializes the HMM state space for this clonal family.
void InitializeTransition ()
Initializes the transition probability matrices between adjacent HMM regions.
void RunForwardAlgorithm ()
Runs the forward algorithm and caches the forward probabilities needed for log-likelihood computation and hidden state sampling.
void ComputeInitialForwardProbabilities ()
Computes the forward probabilities in the V "germline" region.
void SampleInitialState ()
Samples a J "germline" state.
Protected Attributes inherited from linearham::HMM
std::string locus_
YAML::Node cluster_data_
std::map< std::string, std::pair< int, int > > flexbounds_
std::map< std::string, int > relpos_
std::unordered_map< std::string, GermlineGene > ggenes_
std::string alphabet_
Eigen::MatrixXi msa_
std::mt19937 rng_
std::discrete_distribution< int > distr_
std::map< std::string, std::pair< int, int > > vpadding_ggene_ranges_
std::vector< int > vpadding_naive_bases_
std::vector< int > vpadding_site_inds_
std::vector< std::string > vgerm_state_strs_
std::vector< int > vgerm_left_del_
std::vector< int > vgerm_right_del_
std::map< std::string, std::pair< int, int > > vgerm_ggene_ranges_
std::vector< int > vgerm_naive_bases_
std::vector< int > vgerm_germ_inds_
std::vector< int > vgerm_site_inds_
std::vector< std::string > vd_junction_state_strs_
std::vector< int > vd_junction_del_
std::vector< GermlineType > vd_junction_ggene_types_
std::map< std::string, std::pair< int, int > > vd_junction_ggene_ranges_
std::vector< int > vd_junction_naive_bases_
std::vector< int > vd_junction_germ_inds_
std::vector< int > vd_junction_site_inds_
std::vector< std::string > dgerm_state_strs_
std::vector< int > dgerm_left_del_
std::vector< int > dgerm_right_del_
std::map< std::string, std::pair< int, int > > dgerm_ggene_ranges_
std::vector< int > dgerm_naive_bases_
std::vector< int > dgerm_germ_inds_
std::vector< int > dgerm_site_inds_
std::vector< std::string > dj_junction_state_strs_
std::vector< int > dj_junction_del_
std::vector< GermlineType > dj_junction_ggene_types_
std::map< std::string, std::pair< int, int > > dj_junction_ggene_ranges_
std::vector< int > dj_junction_naive_bases_
std::vector< int > dj_junction_germ_inds_
std::vector< int > dj_junction_site_inds_
std::vector< std::string > jgerm_state_strs_
std::vector< int > jgerm_left_del_
std::vector< int > jgerm_right_del_
std::map< std::string, std::pair< int, int > > jgerm_ggene_ranges_
std::vector< int > jgerm_naive_bases_
std::vector< int > jgerm_germ_inds_
std::vector< int > jgerm_site_inds_
std::map< std::string, std::pair< int, int > > jpadding_ggene_ranges_
std::vector< int > jpadding_naive_bases_
std::vector< int > jpadding_site_inds_
Eigen::RowVectorXd vpadding_transition_
Eigen::MatrixXd vgerm_vd_junction_transition_
Eigen::MatrixXd vd_junction_transition_
Eigen::MatrixXd vd_junction_dgerm_transition_
Eigen::MatrixXd dgerm_dj_junction_transition_
Eigen::MatrixXd dj_junction_transition_
Eigen::MatrixXd dj_junction_jgerm_transition_
Eigen::RowVectorXd jpadding_transition_
Eigen::RowVectorXd vpadding_emission_
Eigen::RowVectorXd vgerm_emission_
Eigen::MatrixXd vd_junction_emission_
Eigen::RowVectorXd dgerm_emission_
Eigen::MatrixXd dj_junction_emission_
Eigen::RowVectorXd jgerm_emission_
Eigen::RowVectorXd jpadding_emission_
bool cache_forward_
Eigen::RowVectorXd vgerm_forward_
Eigen::MatrixXd vd_junction_forward_
Eigen::RowVectorXd dgerm_forward_
Eigen::MatrixXd dj_junction_forward_
Eigen::RowVectorXd jgerm_forward_
int vgerm_scaler_count_
std::vector< int > vd_junction_scaler_counts_
int dgerm_scaler_count_
std::vector< int > dj_junction_scaler_counts_
int jgerm_scaler_count_
std::string naive_seq_samp_
std::string vgerm_state_str_samp_
int vgerm_state_ind_samp_
int vgerm_left_del_samp_
int vgerm_right_del_samp_
std::string vgerm_left_insertion_samp_
std::vector< std::string > vd_junction_state_str_samps_
std::vector< int > vd_junction_state_ind_samps_
std::string vd_junction_insertion_samp_
std::string dgerm_state_str_samp_
int dgerm_state_ind_samp_
int dgerm_left_del_samp_
int dgerm_right_del_samp_
std::vector< std::string > dj_junction_state_str_samps_
std::vector< int > dj_junction_state_ind_samps_
std::string dj_junction_insertion_samp_
std::string jgerm_state_str_samp_
int jgerm_state_ind_samp_
int jgerm_left_del_samp_
int jgerm_right_del_samp_
std::string jgerm_right_insertion_samp_
Detailed Description
A star tree HMM implementation (similar to that found in partis). This derived class is used to compute the star tree emission probabilities from partis HMM germline parameter files.
Definition at line 22 of file SimpleHMM.hpp.
Constructor & Destructor Documentation
SimpleHMM()
linearham::SimpleHMM::SimpleHMM (const std::string & yaml_path, int cluster_ind, const std::string & hmm_param_dir, int seed)
SimpleHMM constructor.
Parameters
[in] yaml_path The partis output YAML file path.
[in] cluster_ind An index specifying the clonal family of interest.
[in] hmm_param_dir The directory of partis HMM germline parameter files.
[in] seed The RNG seed.
Definition at line 26 of file SimpleHMM.cpp.
References linearham::HMM::cache_forward_, linearham::HMM::dgerm_scaler_count_, InitializeEmission(), linearham::HMM::jgerm_scaler_count_, linearham::HMM::locus_, and linearham::HMM::vgerm_scaler_count_.
Member Function Documentation
FillGermlineEmission()
void linearham::SimpleHMM::FillGermlineEmission (const std::map< std::string, std::pair< int, int >> & ggene_ranges_, const std::vector< int > & germ_inds_, const std::vector< int > & site_inds_, Eigen::RowVectorXd & emission_, int & scaler_count_) const private
Fills the "germline" emission probability row vector under the star tree assumption.
Parameters
[in] ggene_ranges_ A map that holds start/end indices for the "germline" data structures.
[in] germ_inds_ A vector of "germline" germline position indices.
[in] site_inds_ A vector of "germline" site indices.
[out] emission_ The "germline" emission probability row vector.
[out] scaler_count_ The "germline" scaler count.
Definition at line 95 of file SimpleHMM.cpp.
References linearham::HMM::alphabet_, linearham::GermlineGene::germ_ptr, linearham::HMM::ggenes_, linearham::HMM::msa_, linearham::SCALE_FACTOR, and linearham::ScaleMatrix().
Referenced by InitializeEmission().
FillJunctionEmission()
void linearham::SimpleHMM::FillJunctionEmission (const std::map< std::string, std::pair< int, int >> & ggene_ranges_, const std::vector< int > & naive_bases_, const std::vector< int > & germ_inds_, const std::vector< int > & site_inds_, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, Eigen::MatrixXd & emission_) const private
Fills the "junction" emission probability matrix under the star tree assumption.
Parameters
[in] ggene_ranges_ A map that holds start/end indices for the "junction" data structures.
[in] naive_bases_ A vector of "junction" naive base indices.
[in] germ_inds_ A vector of "junction" germline position indices.
[in] site_inds_ A vector of "junction" site indices.
[in] left_flexbounds A 2-tuple of MSA positions describing the possible "junction" entry locations.
[in] right_flexbounds A 2-tuple of MSA positions describing the possible "junction" exit locations.
[out] emission_ The "junction" emission probability matrix.
Definition at line 160 of file SimpleHMM.cpp.
References linearham::HMM::alphabet_, linearham::D, linearham::GermlineGene::DGermlinePtrCast(), linearham::GermlineGene::germ_ptr, linearham::HMM::ggenes_, linearham::GermlineGene::JGermlinePtrCast(), linearham::HMM::msa_, and linearham::GermlineGene::type.
Referenced by InitializeEmission().
FillPaddingEmission()
void linearham::SimpleHMM::FillPaddingEmission (const std::map< std::string, std::pair< int, int >> & ggene_ranges_, const std::vector< int > & site_inds_, Eigen::RowVectorXd & emission_, int & scaler_count_) const private
Fills the "padding" emission probability row vector associated with the adjacent "germline" region under the star tree assumption.
Parameters
[in] ggene_ranges_ A map that holds start/end indices for the "padding" data structures.
[in] site_inds_ A vector of "padding" site indices.
[out] emission_ The "padding" emission probability row vector.
[out] scaler_count_ The "padding" scaler count.
Definition at line 224 of file SimpleHMM.cpp.
References linearham::HMM::alphabet_, linearham::HMM::ggenes_, linearham::GermlineGene::JGermlinePtrCast(), linearham::HMM::msa_, linearham::SCALE_FACTOR, linearham::ScaleMatrix(), linearham::GermlineGene::type, linearham::V, and linearham::GermlineGene::VGermlinePtrCast().
Referenced by InitializeEmission().
InitializeEmission()
void linearham::SimpleHMM::InitializeEmission () override private virtual
Initializes the emission probability matrices under the star tree assumption.
Implements linearham::HMM.
Definition at line 47 of file SimpleHMM.cpp.
References linearham::HMM::dgerm_emission_, linearham::HMM::dgerm_germ_inds_, linearham::HMM::dgerm_ggene_ranges_, linearham::HMM::dgerm_scaler_count_, linearham::HMM::dgerm_site_inds_, linearham::HMM::dj_junction_emission_, linearham::HMM::dj_junction_germ_inds_, linearham::HMM::dj_junction_ggene_ranges_, linearham::HMM::dj_junction_naive_bases_, linearham::HMM::dj_junction_site_inds_, FillGermlineEmission(), FillJunctionEmission(), FillPaddingEmission(), linearham::HMM::flexbounds_, linearham::HMM::jgerm_emission_, linearham::HMM::jgerm_germ_inds_, linearham::HMM::jgerm_ggene_ranges_, linearham::HMM::jgerm_scaler_count_, linearham::HMM::jgerm_site_inds_, linearham::HMM::jpadding_emission_, linearham::HMM::jpadding_ggene_ranges_, linearham::HMM::jpadding_site_inds_, linearham::HMM::locus_, linearham::HMM::vd_junction_emission_, linearham::HMM::vd_junction_germ_inds_, linearham::HMM::vd_junction_ggene_ranges_, linearham::HMM::vd_junction_naive_bases_, linearham::HMM::vd_junction_site_inds_, linearham::HMM::vgerm_emission_, linearham::HMM::vgerm_germ_inds_, linearham::HMM::vgerm_ggene_ranges_, linearham::HMM::vgerm_scaler_count_, linearham::HMM::vgerm_site_inds_, linearham::HMM::vpadding_emission_, linearham::HMM::vpadding_ggene_ranges_, and linearham::HMM::vpadding_site_inds_.
Referenced by SimpleHMM().
The documentation for this class was generated from the following files:
src/SimpleHMM.hpp
src/SimpleHMM.cpp