linearham: linearham::NPadding Class Reference
linearham::NPadding Class Reference
An abstraction used to represent the padded germline states on the left (right) of V (J) genes.
#include <NPadding.hpp>
Public Member Functions
NPadding (const YAML::Node &root)
Constructor for NPadding starting from a partis YAML file.
double n_transition () const
const Eigen::VectorXd & n_emission () const
Protected Attributes
double n_transition_
Eigen::VectorXd n_emission_
Detailed Description
An abstraction used to represent the padded germline states on the left (right) of V (J) genes.
Definition at line 15 of file NPadding.hpp.
Constructor & Destructor Documentation
NPadding()
linearham::NPadding::NPadding (const YAML::Node & root)
Constructor for NPadding starting from a partis YAML file.
Parameters
[in] root A root node associated with a partis YAML file.
Definition at line 22 of file NPadding.cpp.
References linearham::EPS, linearham::FindGermlineStartEnd(), linearham::GetAlphabet(), linearham::GetAlphabetIndex(), n_emission_, n_transition_, and linearham::ParseStringProbMap().
Member Function Documentation
n_emission()
const Eigen::VectorXd& linearham::NPadding::n_emission () const inline
Definition at line 24 of file NPadding.hpp.
References n_emission_.
n_transition()
double linearham::NPadding::n_transition () const inline
Definition at line 23 of file NPadding.hpp.
References n_transition_.
Member Data Documentation
n_emission_
Eigen::VectorXd linearham::NPadding::n_emission_ protected
Definition at line 18 of file NPadding.hpp.
Referenced by n_emission(), and NPadding().
n_transition_
double linearham::NPadding::n_transition_ protected
Definition at line 17 of file NPadding.hpp.
Referenced by n_transition(), and NPadding().
The documentation for this class was generated from the following files:
src/NPadding.hpp
src/NPadding.cpp