linearham: linearham Namespace Reference
linearham Namespace Reference
Classes
class DGermline
An abstraction used to represent a D germline gene.
class Germline
A class holding germline gene HMM information extracted from a partis YAML file. This information is used to compute (Simple|Phylo)HMM path probabilities.
class GermlineGene
A common class for the different germline gene types.
class HMM
Abstract base class for SimpleHMM and PhyloHMM.
class JGermline
An abstraction used to represent a J germline gene.
class NPadding
An abstraction used to represent the padded germline states on the left (right) of V (J) genes.
class NTInsertion
A class holding non-templated insertion (NTI) HMM information extracted from a partis YAML file. This information is used to compute (Simple|Phylo)HMM path probabilities.
class PhyloHMM
This Phylo-HMM class computes emission probabilities using a phylogenetic tree.
class SimpleHMM
A star tree HMM implementation (similar to that found in partis). This derived class is used to compute the star tree emission probabilities from partis HMM germline parameter files.
class VGermline
An abstraction used to represent a V germline gene.
Typedefs
typedef std::shared_ptr< Germline > GermlinePtr
typedef std::shared_ptr< HMM > HMMPtr
typedef std::shared_ptr< NTInsertion > NTInsertionPtr
typedef std::shared_ptr< PhyloHMM > PhyloHMMPtr
typedef std::shared_ptr< SimpleHMM > SimpleHMMPtr
typedef std::shared_ptr< VGermline > VGermlinePtr
typedef std::shared_ptr< DGermline > DGermlinePtr
typedef std::shared_ptr< JGermline > JGermlinePtr
Enumerations
enum GermlineType { GermlineType::V, GermlineType::D, GermlineType::J }
An enumerated type listing the different germline gene types.
Functions
void CacheGermlineStates (GermlinePtr germ_ptr, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, int relpos, bool left_end, bool right_end, std::vector< std::string > &state_strs_, std::vector< int > &left_del_, std::vector< int > &right_del_, std::map< std::string, std::pair< int, int >> &ggene_ranges_, std::vector< int > &naive_bases_, std::vector< int > &germ_inds_, std::vector< int > &site_inds_)
Caches the "germline" state information for a given germline gene.
void CacheJunctionStates (const GermlineGene &ggene, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, int relpos, bool left_end, std::vector< std::string > &state_strs_, std::vector< int > &del_, std::vector< GermlineType > &ggene_types_, std::map< std::string, std::pair< int, int >> &ggene_ranges_, std::vector< int > &naive_bases_, std::vector< int > &germ_inds_, std::vector< int > &site_inds_)
Caches the "junction" state information for a given germline gene.
void CachePaddingStates (GermlinePtr germ_ptr, std::pair< int, int > leftright_flexbounds, int relpos, bool left_end, std::map< std::string, std::pair< int, int >> &ggene_ranges_, std::vector< int > &naive_bases_, std::vector< int > &site_inds_)
Caches the "padding" state information for a given germline gene.
void ComputeGermlineJunctionTransition (const std::vector< std::string > &germ_state_strs_, const std::map< std::string, std::pair< int, int >> &germ_ggene_ranges_, const std::vector< int > &germ_germ_inds_, const std::vector< int > &germ_site_inds_, const std::vector< std::string > &junction_state_strs_, const std::map< std::string, std::pair< int, int >> &junction_ggene_ranges_, const std::vector< int > &junction_germ_inds_, const std::vector< int > &junction_site_inds_, GermlineType left_gtype, GermlineType right_gtype, const std::unordered_map< std::string, GermlineGene > &ggenes_, Eigen::MatrixXd &germ_junction_transition_)
Computes the "germline"-to-"junction" transition probability matrix.
void ComputeJunctionTransition (const std::vector< std::string > &junction_state_strs_, const std::map< std::string, std::pair< int, int >> &junction_ggene_ranges_, const std::vector< int > &junction_germ_inds_, const std::vector< int > &junction_site_inds_, GermlineType left_gtype, GermlineType right_gtype, const std::unordered_map< std::string, GermlineGene > &ggenes_, Eigen::MatrixXd &junction_transition_)
Computes the "junction" transition probability matrix.
void ComputeJunctionGermlineTransition (const std::vector< std::string > &junction_state_strs_, const std::map< std::string, std::pair< int, int >> &junction_ggene_ranges_, const std::vector< int > &junction_germ_inds_, const std::vector< int > &junction_site_inds_, const std::vector< std::string > &germ_state_strs_, const std::map< std::string, std::pair< int, int >> &germ_ggene_ranges_, const std::vector< int > &germ_germ_inds_, const std::vector< int > &germ_site_inds_, GermlineType left_gtype, GermlineType right_gtype, const std::unordered_map< std::string, GermlineGene > &ggenes_, Eigen::MatrixXd &junction_germ_transition_)
Computes the "junction"-to-"germline" transition probability matrix.
void ComputePaddingTransition (const std::map< std::string, std::pair< int, int >> &ggene_ranges_, const std::unordered_map< std::string, GermlineGene > &ggenes_, Eigen::RowVectorXd &transition_)
Computes the "padding" transition probabilities for the different "germline" states.
void FillTransition (const GermlineGene &from_ggene, const GermlineGene &to_ggene, GermlineType left_gtype, GermlineType right_gtype, int germ_ind_row_start, int germ_ind_col_start, int site_ind_row_start, int site_ind_col_start, int nti_row_start, int nti_col_start, int nti_row_length, int nti_col_length, int germ_row_start, int germ_col_start, int germ_row_length, int germ_col_length, Eigen::Ref< Eigen::MatrixXd > transition_)
Fills a block of the transition probability matrix with transition probabilities between two germline genes.
void ComputeJunctionForwardProbabilities (const Eigen::RowVectorXd &germ_forward_, int germ_scaler_count_, const Eigen::MatrixXd &germ_junction_transition_, const Eigen::MatrixXd &junction_transition_, const Eigen::MatrixXd &junction_emission_, Eigen::MatrixXd &junction_forward_, std::vector< int > &junction_scaler_counts_)
Computes the forward probabilities in the "junction" region.
void ComputeGermlineForwardProbabilities (const Eigen::MatrixXd &junction_forward_, const std::vector< int > &junction_scaler_counts_, const Eigen::MatrixXd &junction_germ_transition_, const Eigen::RowVectorXd &germ_emission_, const Eigen::RowVectorXd &padding_transition_, const Eigen::RowVectorXd &padding_emission_, Eigen::RowVectorXd &germ_forward_, int &germ_scaler_count_)
Computes the forward probabilities in the "germline" region.
void SampleJunctionStates (int germ_state_ind_samp_, const Eigen::MatrixXd &junction_germ_transition_, const std::vector< std::string > &junction_state_strs_, const std::vector< int > &junction_del_, const std::vector< GermlineType > &junction_ggene_types_, const std::vector< int > &junction_naive_bases_, const Eigen::MatrixXd &junction_transition_, const Eigen::MatrixXd &junction_forward_, GermlineType left_gtype, GermlineType right_gtype, std::pair< int, int > left_flexbounds, const std::string &alphabet, std::mt19937 &rng_, std::discrete_distribution< int > &distr_, std::string &naive_seq_samp_, int &germ_left_del_samp_, std::vector< std::string > &junction_state_str_samps_, std::vector< int > &junction_state_ind_samps_, std::string &junction_insertion_samp_, int &germ_right_del_samp_)
Samples a "junction" state.
void SampleGermlineState (const std::vector< int > &junction_state_ind_samps_, const Eigen::MatrixXd &germ_junction_transition_, const std::vector< std::string > &germ_state_strs_, const std::vector< int > &germ_left_del_, const std::vector< int > &germ_right_del_, const std::map< std::string, std::pair< int, int >> &germ_ggene_ranges_, const std::vector< int > &germ_naive_bases_, const std::vector< int > &germ_site_inds_, const Eigen::RowVectorXd &germ_forward_, const std::string &alphabet, std::mt19937 &rng_, std::discrete_distribution< int > &distr_, std::string &naive_seq_samp_, std::string &germ_state_str_samp_, int &germ_state_ind_samp_, int &germ_left_del_samp_, int &germ_right_del_samp_)
Samples a "germline" state.
void StoreGermlinePaddingXmsaIndices (const std::vector< int > &naive_bases_, const std::vector< int > &site_inds_, std::map< std::pair< int, int >, int > &xmsa_ids, Eigen::VectorXi &xmsa_inds_)
Stores the xMSA site indices in the ["germline"|"padding"] region.
void StoreJunctionXmsaIndices (const std::vector< int > &naive_bases_, const std::vector< int > &site_inds_, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, std::map< std::pair< int, int >, int > &xmsa_ids, Eigen::MatrixXi &xmsa_inds_)
Stores the xMSA site indices in the "junction" region.
void StoreXmsaIndex (std::pair< int, int > id, std::map< std::pair< int, int >, int > &xmsa_ids, int &xmsa_ind)
Stores a xMSA site index.
std::pair< std::vector< std::string >, Eigen::VectorXd > ParseStringProbMap (const YAML::Node &node)
Parse a YAML map from strings to probabilities.
std::string GetAlphabet (const YAML::Node &root)
Extract the nucleotide alphabet from a YAML file.
int GetAlphabetIndex (const std::string &alphabet, char base)
Find the alphabet index of the input nucleotide base.
std::regex GetGermlineStateRegex (std::string gname)
Create the regex used to extract germline state labels.
std::regex GetNTIStateRegex (const std::string &alphabet)
Create the regex used to extract NTI state labels.
std::regex GetFrameworkInsertionRegex (const std::string &alphabet)
Create the regex used to extract V/J framework insertions.
std::pair< int, int > FindGermlineStartEnd (const YAML::Node &root, const std::string &gname)
Find the indices corresponding to the start and end of the germline gene.
int ScaleMatrix (Eigen::Ref< Eigen::MatrixXd > m)
Scales a matrix by SCALE_FACTOR as many times as needed to bring all non-zero matrix entries above SCALE_THRESHOLD.
Eigen::RowVectorXi ConvertSeqToInts (const std::string &seq_str, const std::string &alphabet)
Converts a string sequence to an integer sequence according to the alphabet.
std::string ConvertIntsToSeq (const Eigen::RowVectorXi &seq, const std::string &alphabet)
Converts an integer sequence to a string sequence according to the alphabet.
void ColVecMatCwise (const Eigen::Ref< const Eigen::VectorXd > &b, const Eigen::Ref< const Eigen::MatrixXd > &A, Eigen::Ref< Eigen::MatrixXd > B)
This function takes the coefficient-wise product of b and every column of A.
void RowVecMatCwise (const Eigen::Ref< const Eigen::RowVectorXd > &b, const Eigen::Ref< const Eigen::MatrixXd > &A, Eigen::Ref< Eigen::MatrixXd > B)
This function takes the coefficient-wise product of b and every row of A.
std::unordered_map< std::string, GermlineGene > CreateGermlineGeneMap (std::string hmm_param_dir)
Constructs a GermlineGene map from partis HMM germline parameter files.
Variables
const double EPS = 1e-6
The linearham epsilon.
const double SCALE_FACTOR = std::pow(2, 256)
The linearham scale factor for dealing with numeric underflow.
const double SCALE_THRESHOLD = 1.0 / SCALE_FACTOR
The linearham scale threshold for dealing with numeric underflow.
Typedef Documentation
DGermlinePtr
typedef std::shared_ptr<DGermline> linearham::DGermlinePtr
Definition at line 40 of file VDJGermline.hpp.
GermlinePtr
typedef std::shared_ptr<Germline> linearham::GermlinePtr
Definition at line 57 of file Germline.hpp.
HMMPtr
typedef std::shared_ptr<HMM> linearham::HMMPtr
Definition at line 416 of file HMM.hpp.
JGermlinePtr
typedef std::shared_ptr<JGermline> linearham::JGermlinePtr
Definition at line 41 of file VDJGermline.hpp.
NTInsertionPtr
typedef std::shared_ptr<NTInsertion> linearham::NTInsertionPtr
Definition at line 46 of file NTInsertion.hpp.
PhyloHMMPtr
typedef std::shared_ptr<PhyloHMM> linearham::PhyloHMMPtr
Definition at line 130 of file PhyloHMM.hpp.
SimpleHMMPtr
typedef std::shared_ptr<SimpleHMM> linearham::SimpleHMMPtr
Definition at line 50 of file SimpleHMM.hpp.
VGermlinePtr
typedef std::shared_ptr<VGermline> linearham::VGermlinePtr
Definition at line 39 of file VDJGermline.hpp.
Enumeration Type Documentation
GermlineType
enum linearham::GermlineType strong
An enumerated type listing the different germline gene types.
Enumerator
V
D
J
Definition at line 45 of file VDJGermline.hpp.
Function Documentation
CacheGermlineStates()
void linearham::CacheGermlineStates (GermlinePtr germ_ptr, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, int relpos, bool left_end, bool right_end, std::vector< std::string > & state_strs_, std::vector< int > & left_del_, std::vector< int > & right_del_, std::map< std::string, std::pair< int, int >> & ggene_ranges_, std::vector< int > & naive_bases_, std::vector< int > & germ_inds_, std::vector< int > & site_inds_)
Caches the "germline" state information for a given germline gene.
Parameters
[in] germ_ptr A pointer to an object of class Germline.
[in] left_flexbounds A 2-tuple of MSA positions describing the possible "germline" entry locations.
[in] right_flexbounds A 2-tuple of MSA positions describing the possible "germline" exit locations.
[in] relpos The MSA position of the first germline base.
[in] left_end Is a "padding" region to the left of the germline gene?
[in] right_end Is a "padding" region to the right of the germline gene?
[out] state_strs_ A vector of "germline" state names.
[out] left_del_ A vector of "germline" 5' deletion lengths.
[out] right_del_ A vector of "germline" 3' deletion lengths.
[out] ggene_ranges_ A map that holds start/end indices for the "germline" data structures.
[out] naive_bases_ A vector of "germline" naive base indices.
[out] germ_inds_ A vector of "germline" germline position indices.
[out] site_inds_ A vector of "germline" site indices.
Definition at line 466 of file HMM.cpp.
Referenced by linearham::HMM::InitializeStateSpace().
CacheJunctionStates()
void linearham::CacheJunctionStates (const GermlineGene & ggene, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, int relpos, bool left_end, std::vector< std::string > & state_strs_, std::vector< int > & del_, std::vector< GermlineType > & ggene_types_, std::map< std::string, std::pair< int, int >> & ggene_ranges_, std::vector< int > & naive_bases_, std::vector< int > & germ_inds_, std::vector< int > & site_inds_)
Caches the "junction" state information for a given germline gene.
Parameters
[in] ggene An object of class GermlineGene.
[in] left_flexbounds A 2-tuple of MSA positions describing the possible "junction" entry locations.
[in] right_flexbounds A 2-tuple of MSA positions describing the possible "junction" exit locations.
[in] relpos The MSA position of the first germline base.
[in] left_end Is the left end of the germline gene in the "junction" region?
[out] state_strs_ A vector of "junction" state names.
[out] del_ A vector of "junction" 5' and 3' deletion lengths.
[out] ggene_types_ A vector of "junction" germline gene types.
[out] ggene_ranges_ A map that holds start/end indices for the "junction" data structures.
[out] naive_bases_ A vector of "junction" naive base indices.
[out] germ_inds_ A vector of "junction" germline position indices.
[out] site_inds_ A vector of "junction" site indices.
Definition at line 528 of file HMM.cpp.
References linearham::GermlineGene::germ_ptr, and linearham::GermlineGene::type.
Referenced by linearham::HMM::InitializeStateSpace().
CachePaddingStates()
void linearham::CachePaddingStates (GermlinePtr germ_ptr, std::pair< int, int > leftright_flexbounds, int relpos, bool left_end, std::map< std::string, std::pair< int, int >> & ggene_ranges_, std::vector< int > & naive_bases_, std::vector< int > & site_inds_)
Caches the "padding" state information for a given germline gene.
Parameters
[in] germ_ptr A pointer to an object of class Germline.
[in] leftright_flexbounds A 2-tuple of MSA positions describing the possible "padding" exit/entry locations.
[in] relpos The MSA position of the first germline base.
[in] left_end Is a "padding" region to the left of the germline gene?
[out] ggene_ranges_ A map that holds start/end indices for the "padding" data structures.
[out] naive_bases_ A vector of "padding" naive base indices.
[out] site_inds_ A vector of "padding" site indices.
Definition at line 595 of file HMM.cpp.
Referenced by linearham::HMM::InitializeStateSpace().
ColVecMatCwise()
void linearham::ColVecMatCwise (const Eigen::Ref< const Eigen::VectorXd > & b, const Eigen::Ref< const Eigen::MatrixXd > & A, Eigen::Ref< Eigen::MatrixXd > B)
This function takes the coefficient-wise product of b and every column of A.
Parameters
[in] b Input vector.
[in] A Input matrix.
[out] B Output matrix.
\[ B_{i,j} = b_i A_{i,j} \]
Definition at line 195 of file utils.cpp.
Referenced by FillTransition().
ComputeGermlineForwardProbabilities()
void linearham::ComputeGermlineForwardProbabilities (const Eigen::MatrixXd & junction_forward_, const std::vector< int > & junction_scaler_counts_, const Eigen::MatrixXd & junction_germ_transition_, const Eigen::RowVectorXd & germ_emission_, const Eigen::RowVectorXd & padding_transition_, const Eigen::RowVectorXd & padding_emission_, Eigen::RowVectorXd & germ_forward_, int & germ_scaler_count_)
Computes the forward probabilities in the "germline" region.
Parameters
[in] junction_forward_ The forward probabilities associated with the previous "junction" region.
[in] junction_scaler_counts_ The scaler counts associated with the previous "junction" region.
[in] junction_germ_transition_ The "junction"-to-"germline" transition probability matrix.
[in] germ_emission_ The "germline" emission probability row vector.
[in] padding_transition_ The "padding" transition probabilities associated with the "germline" states.
[in] padding_emission_ The "padding" emission probabilities associated with the "germline" states.
[out] germ_forward_ The "germline" forward probability row vector.
[out] germ_scaler_count_ The "germline" scaler count.
Definition at line 1160 of file HMM.cpp.
References ScaleMatrix().
Referenced by linearham::HMM::RunForwardAlgorithm().
ComputeGermlineJunctionTransition()
void linearham::ComputeGermlineJunctionTransition (const std::vector< std::string > & germ_state_strs_, const std::map< std::string, std::pair< int, int >> & germ_ggene_ranges_, const std::vector< int > & germ_germ_inds_, const std::vector< int > & germ_site_inds_, const std::vector< std::string > & junction_state_strs_, const std::map< std::string, std::pair< int, int >> & junction_ggene_ranges_, const std::vector< int > & junction_germ_inds_, const std::vector< int > & junction_site_inds_, GermlineType left_gtype, GermlineType right_gtype, const std::unordered_map< std::string, GermlineGene > & ggenes_, Eigen::MatrixXd & germ_junction_transition_)
Computes the "germline"-to-"junction" transition probability matrix.
Parameters
[in] germ_state_strs_ A vector of "germline" state names.
[in] germ_ggene_ranges_ A map that holds start/end indices for the "germline" data structures.
[in] germ_germ_inds_ A vector of "germline" germline position indices.
[in] germ_site_inds_ A vector of "germline" site indices.
[in] junction_state_strs_ A vector of "junction" state names.
[in] junction_ggene_ranges_ A map that holds start/end indices for the "junction" data structures.
[in] junction_germ_inds_ A vector of "junction" germline position indices.
[in] junction_site_inds_ A vector of "junction" site indices.
[in] left_gtype The germline gene type on the left side of the "junction" region.
[in] right_gtype The germline gene type on the right side of the "junction" region.
[in] ggenes_ A map holding (germline name, GermlineGene) pairs.
[out] germ_junction_transition_ A reference to the "germline"-to-"junction" transition probability matrix.
Definition at line 647 of file HMM.cpp.
References FillTransition(), linearham::GermlineGene::germ_ptr, and linearham::GermlineGene::type.
Referenced by linearham::HMM::InitializeTransition().
ComputeJunctionForwardProbabilities()
void linearham::ComputeJunctionForwardProbabilities (const Eigen::RowVectorXd & germ_forward_, int germ_scaler_count_, const Eigen::MatrixXd & germ_junction_transition_, const Eigen::MatrixXd & junction_transition_, const Eigen::MatrixXd & junction_emission_, Eigen::MatrixXd & junction_forward_, std::vector< int > & junction_scaler_counts_)
Computes the forward probabilities in the "junction" region.
Parameters
[in] germ_forward_ The forward probabilities associated with the previous "germline" region.
[in] germ_scaler_count_ The scaler count associated with the previous "germline" region.
[in] germ_junction_transition_ The "germline"-to-"junction" transition probability matrix.
[in] junction_transition_ The "junction" transition probability matrix.
[in] junction_emission_ The "junction" emission probability matrix.
[out] junction_forward_ The "junction" forward probability matrix.
[out] junction_scaler_counts_ The "junction" scaler counts.
Definition at line 1107 of file HMM.cpp.
References ScaleMatrix().
Referenced by linearham::HMM::RunForwardAlgorithm().
ComputeJunctionGermlineTransition()
void linearham::ComputeJunctionGermlineTransition (const std::vector< std::string > & junction_state_strs_, const std::map< std::string, std::pair< int, int >> & junction_ggene_ranges_, const std::vector< int > & junction_germ_inds_, const std::vector< int > & junction_site_inds_, const std::vector< std::string > & germ_state_strs_, const std::map< std::string, std::pair< int, int >> & germ_ggene_ranges_, const std::vector< int > & germ_germ_inds_, const std::vector< int > & germ_site_inds_, GermlineType left_gtype, GermlineType right_gtype, const std::unordered_map< std::string, GermlineGene > & ggenes_, Eigen::MatrixXd & junction_germ_transition_)
Computes the "junction"-to-"germline" transition probability matrix.
Parameters
[in] junction_state_strs_ A vector of "junction" state names.
[in] junction_ggene_ranges_ A map that holds start/end indices for the "junction" data structures.
[in] junction_germ_inds_ A vector of "junction" germline position indices.
[in] junction_site_inds_ A vector of "junction" site indices.
[in] germ_state_strs_ A vector of "germline" state names.
[in] germ_ggene_ranges_ A map that holds start/end indices for the "germline" data structures.
[in] germ_germ_inds_ A vector of "germline" germline position indices.
[in] germ_site_inds_ A vector of "germline" site indices.
[in] left_gtype The germline gene type on the left side of the "junction" region.
[in] right_gtype The germline gene type on the right side of the "junction" region.
[in] ggenes_ A map holding (germline name, GermlineGene) pairs.
[out] junction_germ_transition_ A reference to the "junction"-to-"germline" transition probability matrix.
Definition at line 812 of file HMM.cpp.
References FillTransition(), linearham::GermlineGene::germ_ptr, and linearham::GermlineGene::type.
Referenced by linearham::HMM::InitializeTransition().
ComputeJunctionTransition()
void linearham::ComputeJunctionTransition (const std::vector< std::string > & junction_state_strs_, const std::map< std::string, std::pair< int, int >> & junction_ggene_ranges_, const std::vector< int > & junction_germ_inds_, const std::vector< int > & junction_site_inds_, GermlineType left_gtype, GermlineType right_gtype, const std::unordered_map< std::string, GermlineGene > & ggenes_, Eigen::MatrixXd & junction_transition_)
Computes the "junction" transition probability matrix.
Parameters
[in] junction_state_strs_ A vector of "junction" state names.
[in] junction_ggene_ranges_ A map that holds start/end indices for the "junction" data structures.
[in] junction_germ_inds_ A vector of "junction" germline position indices.
[in] junction_site_inds_ A vector of "junction" site indices.
[in] left_gtype The germline gene type on the left side of the "junction" region.
[in] right_gtype The germline gene type on the right side of the "junction" region.
[in] ggenes_ A map holding (germline name, GermlineGene) pairs.
[out] junction_transition_ A reference to the "junction" transition probability matrix.
Definition at line 726 of file HMM.cpp.
References FillTransition(), linearham::GermlineGene::germ_ptr, and linearham::GermlineGene::type.
Referenced by linearham::HMM::InitializeTransition().
ComputePaddingTransition()
void linearham::ComputePaddingTransition (const std::map< std::string, std::pair< int, int >> & ggene_ranges_, const std::unordered_map< std::string, GermlineGene > & ggenes_, Eigen::RowVectorXd & transition_)
Computes the "padding" transition probabilities for the different "germline" states.
Parameters
[in] ggene_ranges_ A map that holds start/end indices for the "padding" data structures.
[in] ggenes_ A map holding (germline name, GermlineGene) pairs.
[out] transition_ A reference to the row vector holding the "padding" transition probabilities.
Definition at line 891 of file HMM.cpp.
References linearham::GermlineGene::JGermlinePtrCast(), linearham::GermlineGene::type, V, and linearham::GermlineGene::VGermlinePtrCast().
Referenced by linearham::HMM::InitializeTransition().
ConvertIntsToSeq()
std::string linearham::ConvertIntsToSeq (const Eigen::RowVectorXi & seq, const std::string & alphabet)
Converts an integer sequence to a string sequence according to the alphabet.
Parameters
[in] seq The integer sequence.
[in] alphabet The nucleotide alphabet.
Returns
The string sequence.
Definition at line 175 of file utils.cpp.
Referenced by linearham::PhyloHMM::BuildXmsa().
ConvertSeqToInts()
Eigen::RowVectorXi linearham::ConvertSeqToInts (const std::string & seq_str, const std::string & alphabet)
Converts a string sequence to an integer sequence according to the alphabet.
Parameters
[in] seq_str The string sequence.
[in] alphabet The nucleotide alphabet.
Returns
The integer sequence.
Definition at line 155 of file utils.cpp.
References GetAlphabetIndex().
Referenced by linearham::HMM::InitializeMsa().
CreateGermlineGeneMap()
std::unordered_map< std::string, GermlineGene > linearham::CreateGermlineGeneMap (std::string hmm_param_dir)
Constructs a GermlineGene map from partis HMM germline parameter files.
Parameters
[in] hmm_param_dir The directory of partis HMM germline parameter files.
Returns
A map holding (germline name, GermlineGene) pairs.
Definition at line 46 of file VDJGermline.cpp.
References D, linearham::GermlineGene::germ_ptr, J, linearham::GermlineGene::type, and V.
Referenced by linearham::HMM::HMM().
FillTransition()
void linearham::FillTransition (const GermlineGene & from_ggene, const GermlineGene & to_ggene, GermlineType left_gtype, GermlineType right_gtype, int germ_ind_row_start, int germ_ind_col_start, int site_ind_row_start, int site_ind_col_start, int nti_row_start, int nti_col_start, int nti_row_length, int nti_col_length, int germ_row_start, int germ_col_start, int germ_row_length, int germ_col_length, Eigen::Ref< Eigen::MatrixXd > transition_)
Fills a block of the transition probability matrix with transition probabilities between two germline genes.
Parameters
[in] from_ggene An object of class GermlineGene that represents the germline gene being transitioned from.
[in] to_ggene An object of class GermlineGene that represents the germline gene being transitioned to.
[in] left_gtype The germline gene type of the germline gene being transitioned from.
[in] right_gtype The germline gene type of the germline gene being transitioned to.
[in] germ_ind_row_start The germline position index associated with the first row of the block.
[in] germ_ind_col_start The germline position index associated with the first column of the block.
[in] site_ind_row_start The site index associated with the first row of the block.
[in] site_ind_col_start The site index associated with the first column of the block.
[in] nti_row_start The row index of the transition probability matrix corresponding to the first NTI state of the germline gene being transitioned from.
[in] nti_col_start The column index of the transition probability matrix corresponding to the first NTI state of the germline gene being transitioned to.
[in] nti_row_length The number of rows of the transition probability matrix corresponding to the number of NTI states of the germline gene being transitioned from.
[in] nti_col_length The number of columns of the transition probability matrix corresponding to the number of NTI states of the germline gene being transitioned to.
[in] germ_row_start The row index of the transition probability matrix corresponding to the first germline state of the germline gene being transitioned from.
[in] germ_col_start The column index of the transition probability matrix corresponding to the first germline state of the germline gene being transitioned to.
[in] germ_row_length The number of rows of the transition probability matrix corresponding to the number of germline states of the germline gene being transitioned from.
[in] germ_col_length The number of columns of the transition probability matrix corresponding to the number of germline states of the germline gene being transitioned to.
[out] transition_ The transition probability matrix.
Definition at line 964 of file HMM.cpp.
References ColVecMatCwise(), D, linearham::GermlineGene::DGermlinePtrCast(), linearham::GermlineGene::germ_ptr, linearham::GermlineGene::JGermlinePtrCast(), RowVecMatCwise(), and linearham::GermlineGene::type.
Referenced by ComputeGermlineJunctionTransition(), ComputeJunctionGermlineTransition(), and ComputeJunctionTransition().
FindGermlineStartEnd()
std::pair< int, int > linearham::FindGermlineStartEnd (const YAML::Node & root, const std::string & gname)
Find the indices corresponding to the start and end of the germline gene.
Parameters
[in] root A YAML root node.
[in] gname The germline name.
Returns
A 2-tuple containing the germline start and end indices.
Definition at line 110 of file utils.cpp.
Referenced by linearham::Germline::Germline(), linearham::NPadding::NPadding(), and linearham::NTInsertion::NTInsertion().
GetAlphabet()
std::string linearham::GetAlphabet (const YAML::Node & root)
Extract the nucleotide alphabet from a YAML file.
Parameters
[in] root A YAML root node.
Returns
The alphabet.
Definition at line 43 of file utils.cpp.
Referenced by linearham::Germline::Germline(), linearham::NPadding::NPadding(), and linearham::NTInsertion::NTInsertion().
GetAlphabetIndex()
int linearham::GetAlphabetIndex (const std::string & alphabet, char base)
Find the alphabet index of the input nucleotide base.
Parameters
[in] alphabet The nucleotide alphabet.
[in] base The nucleotide base.
Returns
The alphabet index.
Definition at line 61 of file utils.cpp.
Referenced by ConvertSeqToInts(), linearham::Germline::Germline(), linearham::NPadding::NPadding(), and linearham::NTInsertion::NTInsertion().
GetFrameworkInsertionRegex()
std::regex linearham::GetFrameworkInsertionRegex (const std::string & alphabet)
Create the regex used to extract V/J framework insertions.
Parameters
[in] alphabet The nucleotide alphabet.
Returns
The framework insertion regex.
Definition at line 97 of file utils.cpp.
Referenced by linearham::HMM::SampleNaiveSequence().
GetGermlineStateRegex()
std::regex linearham::GetGermlineStateRegex (std::string gname)
Create the regex used to extract germline state labels.
Parameters
[in] gname The germline name.
Returns
The germline regex.
Definition at line 74 of file utils.cpp.
Referenced by linearham::Germline::Germline(), and linearham::NTInsertion::NTInsertion().
GetNTIStateRegex()
std::regex linearham::GetNTIStateRegex (const std::string & alphabet)
Create the regex used to extract NTI state labels.
Parameters
[in] alphabet The nucleotide alphabet.
Returns
The NTI regex.
Definition at line 87 of file utils.cpp.
Referenced by linearham::NTInsertion::NTInsertion().
ParseStringProbMap()
std::pair< std::vector< std::string >, Eigen::VectorXd > linearham::ParseStringProbMap (const YAML::Node & node)
Parse a YAML map from strings to probabilities.
Parameters
[in] node A YAML map node.
Returns
The parsed YAML map.
Definition at line 20 of file utils.cpp.
References EPS.
Referenced by linearham::Germline::Germline(), linearham::NPadding::NPadding(), and linearham::NTInsertion::NTInsertion().
RowVecMatCwise()
void linearham::RowVecMatCwise (const Eigen::Ref< const Eigen::RowVectorXd > & b, const Eigen::Ref< const Eigen::MatrixXd > & A, Eigen::Ref< Eigen::MatrixXd > B)
This function takes the coefficient-wise product of b and every row of A.
Parameters
[in] b Input vector.
[in] A Input matrix.
[out] B Output matrix.
\[ B_{i,j} = b_j A_{i,j} \]
Definition at line 212 of file utils.cpp.
Referenced by FillTransition().
SampleGermlineState()
void linearham::SampleGermlineState (const std::vector< int > & junction_state_ind_samps_, const Eigen::MatrixXd & germ_junction_transition_, const std::vector< std::string > & germ_state_strs_, const std::vector< int > & germ_left_del_, const std::vector< int > & germ_right_del_, const std::map< std::string, std::pair< int, int >> & germ_ggene_ranges_, const std::vector< int > & germ_naive_bases_, const std::vector< int > & germ_site_inds_, const Eigen::RowVectorXd & germ_forward_, const std::string & alphabet, std::mt19937 & rng_, std::discrete_distribution< int > & distr_, std::string & naive_seq_samp_, std::string & germ_state_str_samp_, int & germ_state_ind_samp_, int & germ_left_del_samp_, int & germ_right_del_samp_)
Samples a "germline" state.
Parameters
[in] junction_state_ind_samps_ The indices of the previously sampled "junction" states.
[in] germ_junction_transition_ The "germline"-to-"junction" transition probability matrix.
[in] germ_state_strs_ A vector of "germline" state names.
[in] germ_left_del_ A vector of "germline" 5' deletion lengths.
[in] germ_right_del_ A vector of "germline" 3' deletion lengths.
[in] germ_ggene_ranges_ A map that holds start/end indices for the "germline" data structures.
[in] germ_naive_bases_ A vector of "germline" naive base indices.
[in] germ_site_inds_ A vector of "germline" site indices.
[in] germ_forward_ The "germline" forward probability row vector.
[in] alphabet The nucleotide alphabet.
[out] rng_ A Mersenne Twister RNG object.
[out] distr_ A discrete distribution object.
[out] naive_seq_samp_ A reference to the naive sequence sample.
[out] germ_state_str_samp_ A reference to the "germline" state sample.
[out] germ_state_ind_samp_ A reference to the "germline" state index sample.
[out] germ_left_del_samp_ A reference to the "germline" 5' deletion length sample.
[out] germ_right_del_samp_ A reference to the "germline" 3' deletion length sample.
Definition at line 1316 of file HMM.cpp.
Referenced by linearham::HMM::SampleNaiveSequence().
SampleJunctionStates()
void linearham::SampleJunctionStates (int germ_state_ind_samp_, const Eigen::MatrixXd & junction_germ_transition_, const std::vector< std::string > & junction_state_strs_, const std::vector< int > & junction_del_, const std::vector< GermlineType > & junction_ggene_types_, const std::vector< int > & junction_naive_bases_, const Eigen::MatrixXd & junction_transition_, const Eigen::MatrixXd & junction_forward_, GermlineType left_gtype, GermlineType right_gtype, std::pair< int, int > left_flexbounds, const std::string & alphabet, std::mt19937 & rng_, std::discrete_distribution< int > & distr_, std::string & naive_seq_samp_, int & germ_left_del_samp_, std::vector< std::string > & junction_state_str_samps_, std::vector< int > & junction_state_ind_samps_, std::string & junction_insertion_samp_, int & germ_right_del_samp_)
Samples a "junction" state.
Parameters
[in] germ_state_ind_samp_ The index of the previously sampled "germline" state.
[in] junction_germ_transition_ The "junction"-to-"germline" transition probability matrix.
[in] junction_state_strs_ A vector of "junction" state names.
[in] junction_del_ A vector of "junction" 5' and 3' deletion lengths.
[in] junction_ggene_types_ A vector of "junction" germline gene types.
[in] junction_naive_bases_ A vector of "junction" naive base indices.
[in] junction_transition_ The "junction" transition probability matrix.
[in] junction_forward_ The "junction" forward probability matrix.
[in] left_gtype The germline gene type of the "junction" 3' end.
[in] right_gtype The germline gene type of the "junction" 5' end.
[in] left_flexbounds A 2-tuple of MSA positions describing the possible "junction" entry locations.
[in] alphabet The nucleotide alphabet.
[out] rng_ A Mersenne Twister RNG object.
[out] distr_ A discrete distribution object.
[out] naive_seq_samp_ A reference to the naive sequence sample.
[out] germ_left_del_samp_ A reference to the "junction" 5' deletion length sample.
[out] junction_state_str_samps_ A reference to the "junction" state samples.
[out] junction_state_ind_samps_ A reference to the "junction" state index samples.
[out] junction_insertion_samp_ A reference to the "junction" NTI sample.
[out] germ_right_del_samp_ A reference to the "junction" 3' deletion length sample.
Definition at line 1222 of file HMM.cpp.
Referenced by linearham::HMM::SampleNaiveSequence().
ScaleMatrix()
int linearham::ScaleMatrix (Eigen::Ref< Eigen::MatrixXd > m)
Scales a matrix by SCALE_FACTOR as many times as needed to bring all non-zero matrix entries above SCALE_THRESHOLD.
Parameters
[out] m Matrix.
Returns
Number of times we multiplied by SCALE_FACTOR.
Definition at line 135 of file utils.cpp.
References SCALE_FACTOR, and SCALE_THRESHOLD.
Referenced by ComputeGermlineForwardProbabilities(), linearham::HMM::ComputeInitialForwardProbabilities(), ComputeJunctionForwardProbabilities(), linearham::SimpleHMM::FillGermlineEmission(), linearham::PhyloHMM::FillGermlinePaddingEmission(), and linearham::SimpleHMM::FillPaddingEmission().
StoreGermlinePaddingXmsaIndices()
void linearham::StoreGermlinePaddingXmsaIndices (const std::vector< int > & naive_bases_, const std::vector< int > & site_inds_, std::map< std::pair< int, int >, int > & xmsa_ids, Eigen::VectorXi & xmsa_inds_)
Stores the xMSA site indices in the ["germline"|"padding"] region.
Parameters
[in] naive_bases_ A vector of ["germline"|"padding"] naive base indices.
[in] site_inds_ A vector of ["germline"|"padding"] site indices.
[out] xmsa_ids A map identifying already cached xMSA site indices.
[out] xmsa_inds_ The xMSA site indices in the ["germline"|"padding"] region.
Definition at line 461 of file PhyloHMM.cpp.
References StoreXmsaIndex().
Referenced by linearham::PhyloHMM::InitializeXmsaStructs().
StoreJunctionXmsaIndices()
void linearham::StoreJunctionXmsaIndices (const std::vector< int > & naive_bases_, const std::vector< int > & site_inds_, std::pair< int, int > left_flexbounds, std::pair< int, int > right_flexbounds, std::map< std::pair< int, int >, int > & xmsa_ids, Eigen::MatrixXi & xmsa_inds_)
Stores the xMSA site indices in the "junction" region.
Parameters
[in] naive_bases_ A vector of "junction" naive base indices.
[in] site_inds_ A vector of "junction" site indices.
[in] left_flexbounds A 2-tuple of MSA positions describing the possible "junction" entry locations.
[in] right_flexbounds A 2-tuple of MSA positions describing the possible "junction" exit locations.
[out] xmsa_ids A map identifying already cached xMSA site indices.
[out] xmsa_inds_ The xMSA site indices in the "junction" region.
Definition at line 489 of file PhyloHMM.cpp.
References StoreXmsaIndex().
Referenced by linearham::PhyloHMM::InitializeXmsaStructs().
StoreXmsaIndex()
void linearham::StoreXmsaIndex (std::pair< int, int > id, std::map< std::pair< int, int >, int > & xmsa_ids, int & xmsa_ind)
Stores a xMSA site index.
Parameters
[in] id A (naive base, MSA position) pair.
[out] xmsa_ids A map identifying already cached xMSA site indices.
[out] xmsa_ind The xMSA site index.
Definition at line 523 of file PhyloHMM.cpp.
Referenced by StoreGermlinePaddingXmsaIndices(), and StoreJunctionXmsaIndices().
Variable Documentation
EPS
const double linearham::EPS = 1e-6
The linearham epsilon.
Definition at line 20 of file utils.hpp.
Referenced by linearham::PhyloHMM::InitializePhyloParameters(), linearham::NPadding::NPadding(), ParseStringProbMap(), and linearham::PhyloHMM::RunPipeline().
SCALE_FACTOR
const double linearham::SCALE_FACTOR = std::pow(2, 256)
The linearham scale factor for dealing with numeric underflow.
Definition at line 22 of file utils.hpp.
Referenced by linearham::SimpleHMM::FillGermlineEmission(), linearham::PhyloHMM::FillGermlinePaddingEmission(), linearham::SimpleHMM::FillPaddingEmission(), linearham::HMM::LogLikelihood(), and ScaleMatrix().
SCALE_THRESHOLD
const double linearham::SCALE_THRESHOLD = 1.0 / SCALE_FACTOR
The linearham scale threshold for dealing with numeric underflow.
Definition at line 24 of file utils.hpp.
Referenced by ScaleMatrix().