name: build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
    steps:
    - uses: actions/checkout@v2
    - name: Checkout tags
      run: git fetch --unshallow origin +refs/tags/*:refs/tags/*
    - name: Set git branch variable
      run: echo ::set-env name=BRANCH::$(git branch --show-current)
    - name: Set git tag variable
      run: if [ $BRANCH == "main" ];then echo ::set-env name=TAG::$(git describe --tags);else echo ::set-env name=TAG::$BRANCH;fi
    - name: Checkout submodules
      shell: bash
      run: |
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Login to Registry
      run: docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password ${{ secrets.QUAY_PASSWORD }}
    - name: Build the Docker image
      run: docker build . -t quay.io/matsengrp/linearham:$TAG
    - name: Run tests in the Docker image
      run: docker run quay.io/matsengrp/linearham:$TAG sh -c "/linearham/_build/test/test"
    - name: Run example in the Docker image
      run: docker run --rm quay.io/matsengrp/linearham:$TAG sh -c "/linearham/test.sh && /linearham/clean.sh"
      #- name: publish to Registry
      #  run: docker push quay.io/matsengrp/linearham:$TAG
    - name: Build documentation
      run: docker run --rm -v $(pwd):/data nakatt/doxygen:1.8.17 Doxyfile
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.2.1
      with:
        ACCESS_TOKEN: ${{ secrets.GH_PAGES_PERSONAL_ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: html
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: 'Linearham Build'
        url: ${{ secrets.SLACK_NOTIFICATION_WEBHOOK}}
