name: Build Test Publish Quay
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . -t quay.io/matsengrp/linearham:test
    - name: Run test in the Docker image
      run: docker run -v $(pwd):/lhtest quay.io/matsengrp/linearham:test /lhtest/test.sh
    - name: Login to Registry
      run: docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password ${{ secrets.QUAY_PASSWORD }}
    - name: publish to Registry
      run: docker push quay.io/matsengrp/linearham:test
